export const SUPPORTED_LOCALES = ['en', 'ru'] as const;
export type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];

const EN = {
  'boot.title':'BRAINROR MERGE','hud.wave':'WAVE {current} / {total}','hud.boss':'BOSS {chapter}','hud.chaosGate':'CHAOS GATE {current} / {total}','hud.fortress':'FORTRESS {hp}','hud.endless':'ENDLESS {stage}','hud.rift':'RIFT {tier}','hud.recruit':'RECRUIT  •  {cost}','hud.anomaly':'ANOMALY {current} / {max}','hud.crownSignal':'CROWN SIGNAL {current} / {max}','hud.upgrades':'UPGRADES','hud.world':'WORLD {number} • {name}','hud.weekly':'WEEKLY','hud.weeklyActive':'WEEKLY {depth}/12',
  'common.claim':'CLAIM','common.claimed':'CLAIMED','common.done':'DONE','common.locked':'LOCKED','common.close':'CLOSE','common.maxed':'MAXED','common.coins':'COINS','common.core':'CORE','common.shard':'SHARD','common.shards':'SHARDS','common.level':'LEVEL {current} / {max}',
  'daily.title':'DAILY CHAOS','daily.streak':'STREAK {current} / 7','daily.nextReward':'NEXT: {coins} COINS{core}','daily.missions':"TODAY'S MISSIONS",'daily.chest':'DAILY CHAOS CHEST','daily.missionProgress':'{current} / {total} MISSIONS','daily.chestCracked':'CHEST CRACKED','daily.bonusClaimed':'BONUS CLAIMED','daily.rewardClaimed':'REWARD CLAIMED','daily.hint':'Finish all three missions to crack the Chaos Chest. Daily reset uses UTC.',
  'weekly.title':'WEEKLY CHAOS RUN','weekly.week':'WEEK {week}','weekly.subtitle':'12 ENCOUNTERS • SAME RULES FOR EVERYONE','weekly.rules':'THIS WEEK\'S RULES','weekly.progress':'CURRENT {current}/12  •  BEST {best}/12','weekly.active':'RUN ACTIVE','weekly.start':'START RUN','weekly.restart':'START NEW ATTEMPT','weekly.claim':'CLAIM {reward}','weekly.complete':'WEEKLY RUN COMPLETE','weekly.note':'Rules reset every Monday at 00:00 UTC. Rewards are claimable once per week.','weekly.rule.overclocked-crew.name':'Overclocked Crew','weekly.rule.overclocked-crew.description':'Crew attacks 10% faster, but the fortress takes 8% more damage.','weekly.rule.thick-static.name':'Thick Static','weekly.rule.thick-static.description':'Enemies gain 18% HP; combat coin rewards gain 18%.','weekly.rule.glass-fortress.name':'Glass Fortress','weekly.rule.glass-fortress.description':'Squad damage +18%, fortress damage taken +18%.','weekly.rule.price-spike.name':'Price Spike','weekly.rule.price-spike.description':'Recruits cost 20% more; combat coin rewards +15%.','weekly.rule.unstable-loot.name':'Unstable Loot','weekly.rule.unstable-loot.description':'Enemies +12% HP, squad damage +10%, combat coins +12%.','weekly.rule.cheap-trouble.name':'Cheap Trouble','weekly.rule.cheap-trouble.description':'Recruits cost 15% less, but enemies gain 15% HP.',
  'lab.title':'CORE LAB','lab.subtitle':'PERMANENT UPGRADES','lab.hint':'Bosses drop Core Shards. Effects apply instantly.',
  'codex.title':'CHAOS CODEX','codex.discovered':'{current} / {total} discovered','codex.discoveries':'DISCOVERIES','codex.forms':'FORMS {start}–{end} / {total}  •  PAGE {page}/{pages}','codex.ascend':'T3 TWINS • SAME RARITY → ASCEND','codex.achievements':'ACHIEVEMENTS','codex.album':'MUTATION ALBUM','codex.albumProgress':'{current} / {total} STATES • {percent}%','codex.albumNext':'NEXT CACHE • {current} / {target}','codex.albumComplete':'ALBUM COMPLETE','codex.albumReward':'{target} STATES • {reward}','codex.mutationStates':'MUTATIONS {current} / 4',
  'revive.title':'FORTRESS CRACKED!','revive.subtitle':'KEEP THE DAMAGE OR RESTART THE FIGHT','revive.watch':'WATCH AD • REVIVE 60 HP','revive.keepDamage':'KEEP ENEMY DAMAGE','revive.retry':'RETRY FREE','revive.retrySub':'ENEMY RETURNS TO FULL HP','revive.note':'Rewarded revive is optional. Free retry is always available.','revive.used':'REVIVE USED','revive.connecting':'CONNECTING…','revive.unavailable':'AD UNAVAILABLE',
  'offline.title':'WELCOME BACK!','offline.subtitle':'THE CREW KEPT SCAVENGING','offline.rewardSub':'OFFLINE COINS • ALREADY YOURS','offline.watchDouble':'WATCH AD • DOUBLE','offline.watchCoins':'WATCH AD • +{coins}','offline.collect':'COLLECT','offline.away':'AWAY FOR {duration}','offline.connecting':'CONNECTING…','offline.doubled':'DOUBLED','offline.unavailable':'AD UNAVAILABLE',
  'draft.title':'CHAOS DRAFT','draft.subtitle':'PICK 1 PERK FOR THIS CHAPTER','draft.status':'CHAPTER {chapter} • DRAFT {checkpoint}/2 • OWNED {owned}/2','draft.pick':'PICK',
  'perk.impact-jelly.name':'Impact Jelly','perk.impact-jelly.description':'+9% squad damage for the rest of this chapter.','perk.tempo-worm.name':'Tempo Worm','perk.tempo-worm.description':'Crew attacks 8% faster for the rest of this chapter.','perk.fortress-foam.name':'Fortress Foam','perk.fortress-foam.description':'Fortress takes 12% less damage this chapter.','perk.bounty-magnet.name':'Bounty Magnet','perk.bounty-magnet.description':'+18% combat coin rewards this chapter.','perk.repair-moss.name':'Repair Moss','perk.repair-moss.description':'Restore +7 extra fortress HP after every cleared wave.','perk.chaos-capacitor.name':'Chaos Capacitor','perk.chaos-capacitor.description':'+25% Chaos Energy gain for the rest of this chapter.',
  'ability.energy':'CHAOS ENERGY {current} / {max}','ability.needTier':'NEED TIER I','ability.wait':'WAIT','ability.tier':'TIER {tier} • {cost}E','ability.haste':'HASTE','ability.guard':'GUARD','ability.nova':'NOVA','ability.jack':'JACK',
  'ability.slipstream-burst.label':'SLIP','ability.slipstream-burst.name':'Slipstream Burst','ability.slipstream-burst.description':'Temporarily accelerates the entire crew.','ability.crust-guard.label':'GUARD','ability.crust-guard.name':'Crust Guard','ability.crust-guard.description':'Temporarily reduces fortress damage taken.','ability.neon-overdrive.label':'NOVA','ability.neon-overdrive.name':'Neon Overdrive','ability.neon-overdrive.description':'Temporarily amplifies all crew projectile damage.','ability.quasar-jackpot.label':'JACK','ability.quasar-jackpot.name':'Quasar Jackpot','ability.quasar-jackpot.description':'Temporarily amplifies encounter coin rewards.',
  'onboarding.merge.title':'MERGE TWINS','onboarding.merge.body':'Drag one glowing twin onto the other. The battle waits for you.','onboarding.recruit.title':'BUILD THE CREW','onboarding.recruit.body':'Tap RECRUIT once. More weirdos mean more automatic firepower.','onboarding.combat.title':'BREAK THE WAVE','onboarding.combat.body':'Your crew attacks automatically. Survive and defeat this target to finish training.'
} as const;
export type TranslationKey = keyof typeof EN;
type Dictionary = Readonly<Record<TranslationKey,string>>;
const RU: Dictionary = {
  'boot.title':'BRAINROR MERGE','hud.wave':'ВОЛНА {current} / {total}','hud.boss':'БОСС {chapter}','hud.chaosGate':'ВРАТА ХАОСА {current} / {total}','hud.fortress':'КРЕПОСТЬ {hp}','hud.endless':'БЕСКОНЕЧНО {stage}','hud.rift':'РАЗЛОМ {tier}','hud.recruit':'ПРИЗЫВ  •  {cost}','hud.anomaly':'АНОМАЛИЯ {current} / {max}','hud.crownSignal':'СИГНАЛ КОРОНЫ {current} / {max}','hud.upgrades':'УЛУЧШЕНИЯ','hud.world':'МИР {number} • {name}','hud.weekly':'НЕДЕЛЯ','hud.weeklyActive':'НЕДЕЛЯ {depth}/12',
  'common.claim':'ЗАБРАТЬ','common.claimed':'ПОЛУЧЕНО','common.done':'ГОТОВО','common.locked':'ЗАКРЫТО','common.close':'ЗАКРЫТЬ','common.maxed':'МАКС.','common.coins':'МОНЕТ','common.core':'ЯДРО','common.shard':'ОСКОЛОК','common.shards':'ОСКОЛКОВ','common.level':'УРОВЕНЬ {current} / {max}',
  'daily.title':'ЕЖЕДНЕВНЫЙ ХАОС','daily.streak':'СЕРИЯ {current} / 7','daily.nextReward':'ДАЛЕЕ: {coins} МОНЕТ{core}','daily.missions':'ЗАДАНИЯ НА СЕГОДНЯ','daily.chest':'СУНДУК ХАОСА','daily.missionProgress':'{current} / {total} ЗАДАНИЙ','daily.chestCracked':'СУНДУК ОТКРЫТ','daily.bonusClaimed':'БОНУС ПОЛУЧЕН','daily.rewardClaimed':'НАГРАДА ПОЛУЧЕНА','daily.hint':'Выполни все три задания, чтобы открыть Сундук Хаоса. Сброс происходит по UTC.',
  'weekly.title':'НЕДЕЛЬНЫЙ ЗАБЕГ ХАОСА','weekly.week':'НЕДЕЛЯ {week}','weekly.subtitle':'12 БОЁВ • ОДИНАКОВЫЕ ПРАВИЛА ДЛЯ ВСЕХ','weekly.rules':'ПРАВИЛА ЭТОЙ НЕДЕЛИ','weekly.progress':'СЕЙЧАС {current}/12  •  РЕКОРД {best}/12','weekly.active':'ЗАБЕГ АКТИВЕН','weekly.start':'НАЧАТЬ ЗАБЕГ','weekly.restart':'НОВАЯ ПОПЫТКА','weekly.claim':'ЗАБРАТЬ {reward}','weekly.complete':'НЕДЕЛЬНЫЙ ЗАБЕГ ПРОЙДЕН','weekly.note':'Правила меняются каждый понедельник в 00:00 UTC. Каждая награда выдаётся один раз за неделю.','weekly.rule.overclocked-crew.name':'Разогнанная команда','weekly.rule.overclocked-crew.description':'Команда атакует на 10% быстрее, но крепость получает на 8% больше урона.','weekly.rule.thick-static.name':'Густая статика','weekly.rule.thick-static.description':'У врагов +18% HP; награды монетами за бой +18%.','weekly.rule.glass-fortress.name':'Стеклянная крепость','weekly.rule.glass-fortress.description':'Урон команды +18%, входящий урон по крепости +18%.','weekly.rule.price-spike.name':'Скачок цен','weekly.rule.price-spike.description':'Призыв дороже на 20%; награды монетами за бой +15%.','weekly.rule.unstable-loot.name':'Нестабильная добыча','weekly.rule.unstable-loot.description':'У врагов +12% HP, урон команды +10%, награды монетами +12%.','weekly.rule.cheap-trouble.name':'Дешёвые проблемы','weekly.rule.cheap-trouble.description':'Призыв дешевле на 15%, но у врагов +15% HP.',
  'lab.title':'ЛАБОРАТОРИЯ ЯДРА','lab.subtitle':'ПОСТОЯННЫЕ УЛУЧШЕНИЯ','lab.hint':'Боссы дают Осколки Ядра. Эффекты применяются сразу.',
  'codex.title':'КОДЕКС ХАОСА','codex.discovered':'открыто {current} / {total}','codex.discoveries':'ОТКРЫТЫЕ ФОРМЫ','codex.forms':'ФОРМЫ {start}–{end} / {total}  •  СТР. {page}/{pages}','codex.ascend':'ДВЕ T3 • ОДНА РЕДКОСТЬ → ВОЗНЕСЕНИЕ','codex.achievements':'ДОСТИЖЕНИЯ','codex.album':'АЛЬБОМ МУТАЦИЙ','codex.albumProgress':'{current} / {total} СОСТОЯНИЙ • {percent}%','codex.albumNext':'СЛЕД. ТАЙНИК • {current} / {target}','codex.albumComplete':'АЛЬБОМ ЗАВЕРШЁН','codex.albumReward':'{target} СОСТОЯНИЙ • {reward}','codex.mutationStates':'МУТАЦИИ {current} / 4',
  'revive.title':'КРЕПОСТЬ РАЗБИТА!','revive.subtitle':'СОХРАНИ УРОН ИЛИ НАЧНИ БОЙ ЗАНОВО','revive.watch':'РЕКЛАМА • ВОСКРЕСНУТЬ С 60 HP','revive.keepDamage':'УРОН ВРАГУ СОХРАНИТСЯ','revive.retry':'ПОВТОРИТЬ БЕСПЛАТНО','revive.retrySub':'ВРАГ ВЕРНЁТСЯ С ПОЛНЫМ HP','revive.note':'Воскрешение за рекламу необязательно. Бесплатный повтор доступен всегда.','revive.used':'ВОСКРЕШЕНИЕ ИСПОЛЬЗОВАНО','revive.connecting':'ПОДКЛЮЧЕНИЕ…','revive.unavailable':'РЕКЛАМА НЕДОСТУПНА',
  'offline.title':'С ВОЗВРАЩЕНИЕМ!','offline.subtitle':'КОМАНДА ПРОДОЛЖАЛА СОБИРАТЬ ДОБЫЧУ','offline.rewardSub':'МОНЕТЫ ЗА ОФЛАЙН • УЖЕ ТВОИ','offline.watchDouble':'РЕКЛАМА • УДВОИТЬ','offline.watchCoins':'РЕКЛАМА • +{coins}','offline.collect':'ЗАБРАТЬ','offline.away':'ТЕБЯ НЕ БЫЛО {duration}','offline.connecting':'ПОДКЛЮЧЕНИЕ…','offline.doubled':'УДВОЕНО','offline.unavailable':'РЕКЛАМА НЕДОСТУПНА',
  'draft.title':'ДРАФТ ХАОСА','draft.subtitle':'ВЫБЕРИ 1 УСИЛЕНИЕ НА ЭТУ ГЛАВУ','draft.status':'ГЛАВА {chapter} • ДРАФТ {checkpoint}/2 • ВЗЯТО {owned}/2','draft.pick':'ВЫБРАТЬ',
  'perk.impact-jelly.name':'Ударное желе','perk.impact-jelly.description':'+9% к урону отряда до конца главы.','perk.tempo-worm.name':'Темпочервь','perk.tempo-worm.description':'Команда атакует на 8% быстрее до конца главы.','perk.fortress-foam.name':'Пена крепости','perk.fortress-foam.description':'Крепость получает на 12% меньше урона в этой главе.','perk.bounty-magnet.name':'Магнит наград','perk.bounty-magnet.description':'+18% монет за бои в этой главе.','perk.repair-moss.name':'Ремонтный мох','perk.repair-moss.description':'После каждой волны крепость восстанавливает ещё 7 HP.','perk.chaos-capacitor.name':'Конденсатор Хаоса','perk.chaos-capacitor.description':'+25% к получению Энергии Хаоса до конца главы.',
  'ability.energy':'ЭНЕРГИЯ ХАОСА {current} / {max}','ability.needTier':'НУЖЕН УРОВЕНЬ I','ability.wait':'ЖДИ','ability.tier':'УРОВЕНЬ {tier} • {cost}E','ability.haste':'УСКОРЕНИЕ','ability.guard':'ЩИТ','ability.nova':'НОВА','ability.jack':'ДЖЕК',
  'ability.slipstream-burst.label':'РЫВОК','ability.slipstream-burst.name':'Потоковый рывок','ability.slipstream-burst.description':'Временно ускоряет всю команду.','ability.crust-guard.label':'ЩИТ','ability.crust-guard.name':'Корковый щит','ability.crust-guard.description':'Временно снижает урон по крепости.','ability.neon-overdrive.label':'НОВА','ability.neon-overdrive.name':'Неоновый форсаж','ability.neon-overdrive.description':'Временно усиливает урон всех снарядов команды.','ability.quasar-jackpot.label':'ДЖЕК','ability.quasar-jackpot.name':'Квазарный джекпот','ability.quasar-jackpot.description':'Временно увеличивает награду монетами за бой.',
  'onboarding.merge.title':'ОБЪЕДИНИ ДВОЙНЮ','onboarding.merge.body':'Перетащи одного светящегося двойника на другого. Бой подождёт.','onboarding.recruit.title':'СОБЕРИ КОМАНДУ','onboarding.recruit.body':'Нажми ПРИЗЫВ один раз. Больше чудиков — больше автоматической огневой мощи.','onboarding.combat.title':'СЛОМАЙ ВОЛНУ','onboarding.combat.body':'Команда атакует автоматически. Выживи и уничтожь цель, чтобы закончить обучение.'
};
const DICTIONARIES: Readonly<Record<SupportedLocale,Dictionary>>={en:EN,ru:RU};
export function normalizeLocale(value:string|null|undefined):SupportedLocale|null{if(!value)return null;const n=value.trim().toLowerCase().replace('_','-');if(n==='en'||n.startsWith('en-'))return'en';if(n==='ru'||n.startsWith('ru-'))return'ru';return null;}
export function resolveLocale(search?:string,languages?:readonly string[]):SupportedLocale{const query=search??(typeof location!=='undefined'?location.search:'');const p=new URLSearchParams(query);const explicit=normalizeLocale(p.get('lang'));if(explicit)return explicit;const preferred=languages??(typeof navigator!=='undefined'?navigator.languages:[]);for(const language of preferred){const r=normalizeLocale(language);if(r)return r;}return'en';}
export function translate(key:TranslationKey,params:Readonly<Record<string,string|number>>={},locale:SupportedLocale=resolveLocale()):string{const template=DICTIONARIES[locale][key]??EN[key];return template.replace(/\{([a-zA-Z0-9_]+)\}/g,(match,token:string)=>{const value=params[token];return value===undefined?match:String(value);});}
export function getDictionary(locale:SupportedLocale):Dictionary{return DICTIONARIES[locale];}
