import { describe, expect, it } from 'vitest';
import { createStarterBoard } from './board';
import { ACHIEVEMENTS, COLLECTION_KEYS, achievementProgress, backfillCollectionProgress, claimAchievement, createDefaultCollectionProgress, discoverCreature, discoverFromBoard, recordLifetimeEvent } from './collectionProgression';
describe('collection progression', () => {
  it('discovers starter creatures from the board without duplicates',()=>{const progress=discoverFromBoard(createDefaultCollectionProgress(),createStarterBoard()); expect(progress.discovered).toEqual(['pinguino-1','toastodilo-1']);});
  it('derives the codex keys from the complete 36-form launch-candidate roster',()=>{expect(COLLECTION_KEYS).toHaveLength(36); for(const key of ['lampalotl-3','vendinguana-3','umbrellama-3','mopossum-3','fanthom-3','socktopus-3','microwhale-3']) expect(COLLECTION_KEYS).toContain(key);});
  it('keeps a long-tail achievement ladder beyond the first-session goals',()=>{expect(ACHIEVEMENTS).toHaveLength(15); expect(ACHIEVEMENTS.some((a)=>a.id==='fusion-overdrive'&&a.target===150)).toBe(true); expect(ACHIEVEMENTS.some((a)=>a.id==='fortress-janitor'&&a.target===300)).toBe(true); expect(ACHIEVEMENTS.some((a)=>a.id==='boss-nightmare'&&a.target===20)).toBe(true);});
  it('backfills lower tiers and minimum legacy stats',()=>{const board=[...createStarterBoard()]; board[0]={id:'legacy',family:'pinguino',level:3,mutation:'none'}; board[1]=null; const progress=backfillCollectionProgress(board,4,2,7,{power:1,armor:2,bounty:0}); expect(progress.discovered).toContain('pinguino-3'); expect(progress.stats.bosses).toBe(3); expect(progress.stats.defeats).toBe(14); expect(progress.stats.recruits).toBe(7); expect(progress.stats.upgrades).toBe(3);});
  it('discovers new roster tiers and rejects unknown collection keys',()=>{const progress=discoverCreature(createDefaultCollectionProgress(),'microwhale-2'); expect(progress.discovered).toEqual(['microwhale-2']); expect(discoverCreature(progress,'stolen-meme-999')).toBe(progress);});
  it('unlocks and claims an achievement once',()=>{const progress=recordLifetimeEvent(createDefaultCollectionProgress(),'merge'); expect(achievementProgress(progress,'first-fusion').ready).toBe(true); const first=claimAchievement(progress,'first-fusion'); const second=claimAchievement(first.progress,'first-fusion'); expect(first.claimed).toBe(true); expect(first.reward.coins).toBe(50); expect(second.claimed).toBe(false);});
  it('derives codex completion from the live roster size',()=>{let progress=createDefaultCollectionProgress(); for(const key of COLLECTION_KEYS) progress=discoverCreature(progress,key); expect(achievementProgress(progress,'codex-complete')).toMatchObject({current:36,target:36,ready:true}); const definition=ACHIEVEMENTS.find((a)=>a.id==='codex-complete'); expect(definition?.description).toContain('36');});
});
